title: Tarefas Linguagens Formais e Automatos
description: Coleção de tarefas de LFA

# Para GitHub Pages em repositório de projeto:
url: "https://marcosbiao.github.io"
baseurl: "/testpages"

# Tema de documentação (sidebar + busca)
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# opcional: ordenação mais previsível quando você não usa nav_order
nav_sort: case_insensitive

search_enabled: true

aux_links:
  "Repositório no GitHub":
    - "https://github.com/marcosbiao/testpages"
